version: '3.2'
networks:
    mynetwork:

services:
  broker-secure:
    container_name: broker-secure
    image: vernemq/vernemq:1.10.2-1-alpine
    depends_on: 
      - db
    networks:
      - mynetwork
    volumes:
      - ./certs-v4/:/etc/ssl/
    ports:
        - 8888:8888
        - 8883:8883
    environment: 
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_LISTENER__HTTP__DEFAULT=127.0.0.1:8888
      - DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT=0.0.0.0:8883
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_POSTGRES__ENABLED=on
      - DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY=on
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__HOST=db
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PORT=5432
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__USER=admin
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD=admin
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__DATABASE=acls
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD_HASH_METHOD=crypt
      - DOCKER_VERNEMQ_LISTENER__SSL__CAFILE=/etc/ssl/ca.crt
      - DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE=/etc/ssl/server/LANCEY-FPINAUD.crt
      - DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE=/etc/ssl/server/LANCEY-FPINAUD.key
      - DOCKER_VERNEMQ_LISTENER__SSL__REQUIRE_CERTIFICATE=on
  db:
    container_name: db
    image: postgres:latest
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: acls
    volumes:
      - ./schemas:/docker-entrypoint-initdb.d:ro
    ports:
      - 5432:5432
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    networks:
      - mynetwork
    environment:
      - TZ=Europe/Paris
    ports:
      - 1880:1888
    volumes:
      - ./node-red-data:/data