version: '3.2'
networks:
    mynetwork:

services:
  broker-secure:
    container_name: broker-secure
    image: vernemq/vernemq:1.10.2-1-alpine
    depends_on: 
      - db
    networks:
      - mynetwork
    volumes:
      - ./certs-v4/:/etc/ssl/
    ports:
        - 8888:8888
        - 1883:1883
    environment: 
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_LISTENER__HTTP__DEFAULT=127.0.0.1:8888
      - DOCKER_VERNEMQ_LISTENER__TCP__DEFAULT=0.0.0.0:1883
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_POSTGRES__ENABLED=on
      - DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY=on
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__HOST=db
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PORT=5432
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__USER=admin
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD=admin
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__DATABASE=acls
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD_HASH_METHOD=crypt
  db:
    container_name: db
    image: postgres:latest
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: acls
    volumes:
      - ./schemas:/docker-entrypoint-initdb.d:ro
    ports:
      - 5432:5432