{
 "title": "temp/hum MQTT",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS \"time\",\n  value\nFROM temperature\nWHERE\n  $__timeFilter(hour)\nORDER BY hour"
    }
   ]
  },
  {
   "title": "Records",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(hour,10m,previous),\n  count(value) AS \"value\"\nFROM temperature\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS \"time\",\n  value\nFROM humidity\nWHERE\n  $__timeFilter(hour)\nORDER BY hour"
    }
   ]
  },
  {
   "title": "Records",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(hour,10m,previous),\n  count(value) AS \"value\"\nFROM humidity\n"
    }
   ]
  }
 ]
}